### ISSUE TITLE
[Feature]: 초성, 종성, 중성에 일관된 변수명을 사용하기

### ISSUE THREAD

**Issue by okinawaa** [toss/es-hangul#131]
### Description

@crucifyer 님의 코맨트를 인용합니다.

>chosung이라는 것도 choseong이라는 함수로 변경하면 어떨까요? hangul은 표준이지만 chosung은 표준이 아닌것 같아서 표준대로 혹은 정해진 규칙대로하면 일관된 인터페이스를 만들 수 있을 것 같아요 좋을 것 같아요
http://roman.cs.pusan.ac.kr/result_all.aspx?input=%ec%b4%88%ec%84%b1
https://www.unicode.org/charts/PDF/U1100.pdf
unicode.org 에서도 CHOSEONG, JUNGSEONG, JONGSEONG 이네요.

**Comment by Collection50** [comment]
안녕하세요 @okinawaa !

제가 해당 이슈를 맡고 싶습니다 :)

**Comment by okinawaa** [comment]
@Collection50 너무 좋아요! 먼저 말씀해주셔서 정말 감사합니다!
