### ISSUE TITLE
[Feature]: 애너그램 여부를 확인하는 함수

### ISSUE THREAD

**Issue by po4tion** [toss/es-hangul#142]
### Description

입력으로 주어진 값들이 서로 애너그램인지 확인하는 기능

*애너그램 : 일종의 말장난으로 어떠한 단어의 문자를 재배열하여 다른 뜻을 가지는 다른 단어로 바꾸는 것을 말한다.

### Possible Solution

```ts
/**
* @description 주어진 두 개의 한글 문자열이 애너그램인지 확인합니다.
* @param origin 원본 한글 문자열
* @param targe 비교하고자 하는 한글 문자열
* @return 두 문자열이 애너그램이면 true, 아니면 false를 반환합니다.
* @example
* checkAnagramHangul("장화", "화장")
* checkAnagramHangul("임무", "미움")
*/
function checkAnagramHangul(origin, target): boolean {
  return true or false;
}
```

## 예상 사용 사례

1. 언어 게임 및 퍼즐
2. 암호화
3. 텍스트 분석
4. 창의적 글쓰기 도구

**Comment by po4tion** [comment]
@okinawaa es-hangul에 해당 기능이 만들어져도 괜찮을까요?

**Comment by okinawaa** [comment]
애너그램보다는, 좀 더 일반적으로 
두개의 문자열이 구성되있는 한글 letter가 같냐가 함수의 목적인것 같은데요. 
예상 사용 사례에 공감이 되어서, es-hangul에 추가되면 좋겠다고 생각해요

아래와 같이 간단히 생각해봤습니다, 완전한 한글 Letter가 안들어오는경우들도, 고려가 되어야겠지만요

```tsx
/**
* @description 주어진 두 개의 한글 문자열이 같은 문자들로 구성되어 있는지 확인합니다.
* @param origin 원본 한글 문자열
* @param target 비교하고자 하는 한글 문자열
* @return 두 문자열이 같은 문자들로 구성되어 있으면 true, 아니면 false를 반환합니다.
* @example
* isHangulLetterCompositionEqual("장화", "화장")
* isHangulLetterCompositionEqual("임무", "미움")
*/
function isHangulLetterCompositionEqual(origin, target) {
  if (origin.length !== target.length) {
    return false;
  }
  
  const sortString = (str) => str.split('').sort().join('');
  
  return sortString(origin) === sortString(target);
}```

**Comment by po4tion** [comment]
제가 생각하고 있는 기능과는 좀 다른 것 같아요.
일단 첫번째 조건문으로 길이를 확인하고 `false`를 반환하는데요. 이 애너그램 기능은 길이와는 상관이 없습니다.

예를 들어, "괌"이라는 글자가 `origin`이고, "고마"가 `target`이라면 이는 `true`를 반환해야 합니다.

**Comment by okinawaa** [comment]
es-hangul 라이브러리는 최대한 원자적인 함수들을 제공하고, 사용자가 이 작은 함수들을 이용하여 라이브러리의 조합력을 극대화하여 다양한 요구사항을 반영할 수 있으면 좋겠습니다.

제시해주신 애너그램과 같은 고수준의 API를 제공하기보다는, 말씀해주신 요구사항을 보면 disassembleHangul 이나, javascript split funciton을 이용해 어느정도 라이브러리를 사용하는 개발자가 자신의 비즈니스에 맞게 쉽게 구현할 수 있을 것 같다고 생각해요. 
그래서 이러한 고수준의 API는 es-hangul에서 제공되지 않았으면 하는 마음입니다.
