### ISSUE TITLE
[Bug]: 문서가 최신화 되지 않습니다.

### ISSUE THREAD

**Issue by okinawaa** [toss/es-hangul#147]
### Bug description

main 브랜치에 docs 코드베이스가 변경되어도 문서가 재배포 되지 않습니다.

### Expected behavior

docs 코드베이스를 수정한 코드가 main에 머지되면 문서가 재배포 되어야합니다.

**Comment by manudeli** [comment]
https://github.com/toss/es-hangul/pull/112#issuecomment-2143482478

@raon0211 이 방법으로 해결할 수 있어요! 저한테 vercel 권한이 있는데 제가 추가할게요

**Comment by manudeli** [comment]
<img width="948" alt="image" src="https://github.com/toss/es-hangul/assets/61593290/d5af49ae-6748-49c8-93e0-f00aa90b9305">

추가했습니다 다음 배포부터 해결될 것 같습니다

**Comment by manudeli** [comment]
@okinawaa 해결되면 close 해주세요

**Comment by manudeli** [comment]
<img width="1242" alt="image" src="https://github.com/toss/es-hangul/assets/61593290/437242f7-6679-4d21-8e75-989d17cdb3c8">

현재 에러는 이래요. next build 전에 es-hangul build를 해야하는 것 같은데 배포 과정 수정해볼게요

**Comment by manudeli** [comment]
@okinawaa 성공한 것 같아요. main 브랜치 vercel deploy status에도 배포 잘 된 것으로 초록색 동그라미 나오고 있는데 잘 반영되었는지 확인 바라요

<img width="1257" alt="image" src="https://github.com/toss/es-hangul/assets/61593290/9a29f3a8-8eca-4436-85a3-efd0466e6404">

Turborepo를 사용하는 경우엔 따로 설정할 필요가 없는데 es-hangul은 turbo를 사용하지 않아서 vercel build를 사용하지 못하는 모양이에요. 그래서 아래와 같이 매뉴얼로 빌드하도록 설정했슴다

<img width="953" alt="image" src="https://github.com/toss/es-hangul/assets/61593290/4adaeabc-1162-4644-8e4f-bd5a8868d881">


문제 해결되었으면 close 바랍니다

**Comment by okinawaa** [comment]
잘 배포되는것 확인했습니다~~! 감사해용 !!
