### ISSUE TITLE
[Feature]: 정해진 일관된 이름 짓기 규칙에 알맞게 함수명 수정하기 

### ISSUE THREAD

**Issue by okinawaa** [toss/es-hangul#170]
### Description

```tsx
import { z } from 'zod' // 사용성에 집중
z.object()
z.number()

import hangul from 'hangul' // zod와 같은 방식으로도 제공
hangul.josa()
hangul.getSimilarity()
hangul.chosungIncludes()
hangul.disassemble()
hangul.disassembleToGroups()

import { josa, getSimilarity, chosungIncludes, disassemble, disassembleToGroups } from 'hangul' // 나눠서도 제공
josa()
getSimilarity()
chosungIncludes()
disassemble()
disassembleToGroups()
```

**Comment by okinawaa** [comment]
@Collection50 님께서 맡아주신다하여서 감사합니다!

**Comment by Collection50** [comment]
작업 진행 중입니다 !

**Comment by okinawaa** [comment]
@Collection50 이 함수명 수정하기 기능은 너무 큰 작업이므로, v1에서 여러개의 메서드를 공존시켜서 관리포인트를 늘리는것 보다는
#176 에서 논의된 결과로 특정 함수들은 제거하고 그와 동시에 함수명 이름 변경(이 이슈) 도 한꺼번에 진행하고자 합니다.

그래서 몇 가지, 변경 사항은 이미 [v2](https://github.com/toss/es-hangul/tree/v2) branch에 머지되었으며 
리뷰 관리를 위해 진행해주신 #191 처럼 큰 PR보다, 작은 단위의 PR을 올려주시면 보다 리뷰하기 편할 것 같습니다!

**이미 진행된 함수들은 #191 에서 제거해주시길 바라며, 작은 단위의 PR을 v2을 base branch로 PR을 생성해주시면 정말 감사하겠습니다** 🙇 

정리하자면 다음과 같습니다.
v1에서의 운영공수를 올리기 보다는, v2로 빠르게 버전업그레이드를 하고자 합니다.

1. hangul을 제거하는 함수명을 수정합니다.
2. 불필요한 함수들을 제거합니다.

항상 너무 좋은 기여 감사드리며, 더 나은 의견있으시다면 언제든 말씀해주세요!

**Comment by Collection50** [comment]
@okinawaa 

말씀해주신 1, 2번을 v2에 머지하는 것이 좋다고 이해했는데 맞을까요??
만약 맞다면 #191 을 2개로 쪼개어 작업한 후, v2에 작업하겠습니다.

기존 PR을 지속적으로 확인하여, `acronymizeHangul`, `extractHangul` 제거, `disassemble` 류 함수에서 hangul 제거 작업 또한 #191 에서 진행했습니다. (이미 v2에서 삭제된 메서드들은 삭제되어 있습니다 !!)
기존의 PR 자체가 v2에 만족되도록 1, 2번을 모두 만족하게 작업했다고 생각했습니다 !!

제가 잘못 이해한 부분이 있거나 추가적으로 말씀해주실 부분을 남겨주시면 감사하겠습니다~!

**Comment by okinawaa** [comment]
현재 #191 의 변경사항은 base branch가 main을 바라보고있어서 Breaking Change가 발생하면 안된다고 생각해요.
Breaking Change가 발생하는 변경사항은 v2를 바라보도록 PR을 올려주시면 좋을 것 같습니다!

현재 #191 이 머지되면, 1버전임에도 불구하고, 함수명 변경과, 함수 삭제가 발생하므로 es-hangul을 사용하는 개발자들은 혼동할 것 같아요!

**Comment by Collection50** [comment]
@okinawaa 넵 이해했습니다 !!

**Comment by okinawaa** [comment]
@Collection50  넵 감사합니다!! v2를 바라보도록 해서 새로운 PR을 올려주시면 좋을 것 같아요!
현재는 acronymizeHangul가 v2에서 이미 삭제되었는데, #191 에서 또 acronymizeHangul 가 삭제되었다고 file change가 잡히고 있어서요!
