### ISSUE TITLE
HANGUL_CHARACTERS_BY_FIRST_INDEX, HANGUL_CHARACTERS_BY_MIDDLE_INDEX, HANGUL_CHARACTERS_BY_LAST_INDEX

### ISSUE THREAD

**Issue by manudeli** [toss/es-hangul#190]
HANGUL_CHARACTERS_BY_FIRST_INDEX
HANGUL_CHARACTERS_BY_MIDDLE_INDEX
HANGUL_CHARACTERS_BY_LAST_INDEX
이것도 초,중,종으로 통일이 필요하지 않을까요?

_Originally posted by @crucifyer in https://github.com/toss/es-hangul/issues/138#issuecomment-2227732099_

**Comment by Collection50** [comment]
제가 해당 PR을 맡았었는데, 추가적으로 작업하고 싶습니다 ! 👍
