### ISSUE TITLE
[Feature]: v2 마이그레이션 전략

### ISSUE THREAD

**Issue by manudeli** [toss/es-hangul#216]
### Description

문서에서 v2가 준비되고 있음을 표시하고 v2.es-hangul.slash.page로 갈 수 있으면 좋겠어요

최근 라이브러리 유저가 점점 늘어나고 있는만큼 이 기능이 준비되거나 빠르게 v2로 넘어가면 브레이킹체인지에 대한 대비가 가능할 것 같아요

Action Items
1. v2 Beta 버전 배포
2. v2.es-hangul.slash.page 배포
3. v1.es-hangul.slash.page 에 v2 준비를 표기

**Comment by okinawaa** [comment]
우선, 빠르게 v2로 넘어가는것이 중요하다고 생각합니다.

v1 => v2에 대한 변경사항은 깃허브 이슈나 PR, CHANGELOG.md에 꽤 자세하게 남을 것 같아서.
beta, subdomain등의 방법을 이용해서 여러 관리포인트를 늘리기 보다는 빠른 v2배포를 진행하고자 합니다.

**Comment by okinawaa** [comment]
@manudeli 님 좋은 의견감사합니다!
v3올라갈때는 고려해보도록 할게요!
