### ISSUE TITLE
[Feature]: 숫자를 날짜를 나타내는 순우리말로 바꿔주는 함수

### ISSUE THREAD

**Issue by BO-LIKE-CHICKEN** [toss/es-hangul#217]
### Description

안녕하세요 아래와 같은 함수가 `es-hangul`의 목적성에 맞고, 필요하다면 구현해 보고싶습니다.

**숫자를 날짜를 나타내는 순우리말로 바꿔주는 함수를 제안**드립니다.

#### 제안 배경

![thumbnail-example](https://img.youtube.com/vi/B2ZEAApi5m8/0.jpg)

생각보다 많은 사람들이 날짜과 관련된 순우리말을 혼동하는 경우가 있습니다.  이런 경우에 사용할 수 있는 함수가 있다면 좋을 것 같아요.

### Possible Solution

```ts
/**
 * 숫자를 순 우리말 날짜로 변환합니다.
 * @param num 변환하고자 하는 날짜
 * @returns 순 우리말 날짜로 변환된 텍스트
 */
function date(num: number): string {
    return "순 우리말 날짜"; 
}
```

```ts
test('숫자를 순 우리말 날짜로 바꿔야 한다.', () => {
    expect(hangul.date(3)).toEqual('사흘');
})

test('숫자를 순 우리말 날짜로 바꿔야 한다.', () => {
    expect(hangul.date(4)).toEqual('나흘');
})
```

#### 예상 사용사례 

```ts
const remainingDate = 3;
console.log(`신용점수 올리기는 ${hangul.date(remainingDate)}` 뒤에 다시 시도할 수 있어요);
// 출력: 신용점수 올리기는 사흘 뒤에 다시 시도할 수 있어요

const maximumDate = 10;
console.log(`결과가 나오기 까지는 영업일을 제외하고 최대 ${maximumDate}`이 걸릴 수 있어요;
// 출력: 결과가 나오기 까지는 영업일을 제외하고 최대 열흘이 걸릴 수 있어요
```

**Comment by okinawaa** [comment]
너무 좋은 것 같아요.

한국어만의 날짜 규칙도 존재하고, 실제로 애플리케이션 개발하면서 많이 사용할 부분이기때문에 es-hangul에서 제공해줘야한다고 생각합니다.

**Comment by okinawaa** [comment]
인자로는 숫자 몇 까지 받으면 될까요?

**Comment by BO-LIKE-CHICKEN** [comment]
> 인자로는 숫자 몇 까지 받으면 될까요?

결론부터 말씀드리면 1부터 30까지 지원하는 것으로 시작하는 편이 좋아보입니다 🙏🏻

하지만, 아래의 부분에서 꽤나 고민 중이에요 🫠

아래의 이미지 (출처: [국립국어원 X](https://x.com/urimal365/status/1288332464469839872/photo/4))에 따르면 29일(스무아흐레)까지는 명확하지만 
30일의 경우에는 "서른날"로 표현하거나 "그믐"으로(말일인 경우) 표현하는 규칙이 있는데 이 부분은 어떻게 다뤄야할지에 대하여 고민이 해결되지 않았어요. 

그래서
1. 이 함수가 사용될 예시를 생각하고
2. 명확한 기준이 있는 날짜를 고려했을 때

30까지를 인자로 받고 30의 경우에는 "서른날"로 바꾸는 방식으로 구현하려 합니다.

![image](https://github.com/user-attachments/assets/780dd457-1ea3-4977-89e3-1a072ca4064f)
![image](https://github.com/user-attachments/assets/188c1b2e-9d72-4f24-9ed7-2ac05500d321)


+ 달을 다루는 순 우리말에 대한 부분은 정말 쓰이지 않을 뿐더러, 구현이 필요한 상황이 오면 두 번째 인자에 `options`로  받아오면 좋겠다는 생각이 들었습니다. 🙂
