### ISSUE TITLE
[Feature]: 무작위의 한국어 이름을 반환해주는 함수가 있으면 좋을 것 같아요  

### ISSUE THREAD

**Issue by novice0840** [toss/es-hangul#253]
### Description

한국어 이름을 무작위하게 반환해 주는 함수가 있으면 임시 한국인 이름 목록이 필요할 때 유용하게 쓰일 수 있을 것 같아요. 

### Possible Solution

const name = randomName()

console.log(name) // 김철수

### etc.

혹시 괜찮으시다면 저를 assignee로 지정해주시면 제가 만들어 볼 수도 있을 것 같습니다.

**Comment by okinawaa** [comment]
안녕하세요~! 
이 기능이 개발자들이, 한글의 복잡한 도메인을 다루는데 많은 도움이 될까요?!

니즈는 있을 것 같다고 생각하는데, 이름을 생성하는데 수 많은 요구사항이 있을 것(몇 글자, 이름이 자연스러워야 하는지 등등..) 같다고 생각했어요.
조금 더 구체적으로 이 기능이 필요한지 고민이 필요해보여요!

**Comment by po4tion** [comment]
@novice0840 님 안녕하세요!

해당 기능은 한글 도메인에 대한 지식이 없어도, 이를 필요로 하는 개발자들이 충분히 구현할 수 있지 않을까요?

**Comment by okinawaa** [comment]
추가적인 논의가 진행되지 않아서 닫도록 할게요!
이 기능이 한글의 복잡한 도메인을 다루는데 es-hangul을 사용하시는 개발자분들께 도움이 된다고 생각하시면, 다시 이슈를 만들어주세요! 
감사합니다
