### ISSUE TITLE
[Bug]:새로운 API가 추가되는 버전이 문서에 명시되면 좋겠어요

### ISSUE THREAD

**Issue by kmsk99** [toss/es-hangul#262]
### Bug description

numberToHangulMixed와 같은 api가 [문서](https://es-hangul.slash.page/docs/api/numberToHangulMixed)와 main 코드 브랜치에는 구현되어있지만,
최신 npm인 2.1.0 버전에서는 구현되어있지 않아요.

또한 문서의 사용해보기에도 api가 작동하지 않아요.

### Expected behavior

문서에 새로운 기능이 추가되는 버전을 명시하거나, 아직 추가되지 않았다는 플래그를 추가하면 좋겠어요.

### Possible Solution

문서에 새로운 기능이 추가되거나 기능이 변경되었음을 알려주는 change log를 추가하면 좋을것같아요.

**Comment by okinawaa** [comment]
이슈레이징 감사합니다! 2.1.0 에서 배포가 멈춰있었군요, 우선 원인 파악 및 해결해보고 
말씀해주신 문서화도 고민해볼게요!

**Comment by okinawaa** [comment]
<img width="1089" alt="image" src="https://github.com/user-attachments/assets/cff523e1-868f-4c17-aa7d-287846adf54a">

위와 같은 오류가 발생중입니다

**Comment by okinawaa** [comment]
배포 및 CHANGELOG.md에 추가된 버전 적어뒀어요.
감사합니다!
