### ISSUE TITLE
[Feature]: 한글 검색 기능이 있다면 어떨까요?

### ISSUE THREAD

**Issue by LEEGURTS** [toss/es-hangul#304]
### Description

사용자가 입력을 다 마치지 않더라도 비교가 가능하게 하는 기능도 좋을 거 같아요

검색기능 구현시에 유용하게 쓰일거 같아요.

예시로는 
"압구정 로데오" 검색시에
"압구저" 까지만 검색해도 나오고, "압구점" 이라고 검색하면 나오지 않게요!

### Possible Solution

검색("압구정로데오", "ㅈㄹㄷㅇ") true
검색("압구정로데오","압구저") true
검색("압구정로데오","압구점") false

### etc.

정식으로 구현하게 되게 된다면 컨트리뷰션도 해보고 싶습니다!

**Comment by okinawaa** [comment]
안녕하세요! 좋은 의견 감사해요
과거에 
chosungIncludes, hangulInclude라는 함수가 있었지만, 2버전대부터는 삭제가 되었어요.

삭제된 이유에서는 한글을 다루는데 필요한 한글관련 도메인지식이 해당 함수를 구현하는데에는 필요하지 않았기 때문입니다!

관련 PR 목록 첨부드릴게요!

- #188 
- #197
