### ISSUE TITLE
[Docs]: 공식 문서 최신화

### ISSUE THREAD

**Issue by evan-moon** [toss/es-hangul#58]
### Description

https://github.com/toss/es-hangul/pull/36
https://github.com/toss/es-hangul/pull/53

두 PR을 통해 추가된 함수에 대한 내용을 문서에 추가해야합니다.

**Comment by okinawaa** [comment]
제가 추가해둘게요!

**Comment by okinawaa** [comment]
#138 머지되면 진행해둘게요!
