### ISSUE TITLE
[Feature]: Codecov 설정 필요

### ISSUE THREAD

**Issue by manudeli** [toss/es-hangul#63]
### Description

https://es-hangul.slash.page/docs/introduction
unknown제거를 위해 codecov설정 필요합니다

<img width="903" alt="image" src="https://github.com/toss/es-hangul/assets/61593290/825c25de-6495-4354-87a3-e38f67a7e291">

### Possible Solution

codecov는 open source에 무료로 제공되는 것으로 알고 있습니다.
<img width="1231" alt="image" src="https://github.com/toss/es-hangul/assets/61593290/7cdff300-fe97-4263-9263-7e5ea4d800b3">

1. 이 레포지토리에 GitHub bot 설치가 필요합니다.
https://github.com/apps/codecov

2. codecov.yml이 추가와 coverage관련 파일의 업로드를 위해 ci에 추가되어야합니다.
codecov.yml로 설정 PR은 올려놓겠습니다. Circle CI를 사용중으로 보이는데 업로드 방식은 토스에서 추가해주시면 좋겠어요
https://about.codecov.io/tool/circleci/

**Comment by okinawaa** [comment]
<img width="1600" alt="image" src="https://github.com/toss/es-hangul/assets/69495129/a88f69b4-eeb7-4417-9613-804dadecf3b4">

main기준으로 정상적으로 커버리지 측정되는 것 확인했어요!

**Comment by manudeli** [comment]
> <img alt="image" width="1600" src="https://private-user-images.githubusercontent.com/69495129/324253907-a88f69b4-eeb7-4417-9613-804dadecf3b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3MTQwNzksIm5iZiI6MTcxMzcxMzc3OSwicGF0aCI6Ii82OTQ5NTEyOS8zMjQyNTM5MDctYTg4ZjY5YjQtZWViNy00NDE3LTk2MTMtODA0ZGFkZWNmM2I0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDE1MzYxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2NDk5MDg0MTBmMWFmOWM3MGNkYjQwMzNjZTViMzY4ZDQzNWJhYTc3NGMyMjJmZTI4MGRiOTk3MWZjOWE3ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2cPuY2nSsTNvpMlHP0F9LFmNfUKz4aMLZNRe-CeeicQ">
> main기준으로 정상적으로 커버리지 측정되는 것 확인했어요!

좋아요 ㅎㅎ es-hangul을 더 신뢰할 수 있는 라이브러리로!
