### ISSUE TITLE
[Chore]: package.json 내 repository, website, bugs 필드 추가

### ISSUE THREAD

**Issue by evan-moon** [toss/es-hangul#72]
### Description

<img width="1325" alt="스크린샷 2024-04-22 오전 10 45 29" src="https://github.com/toss/es-hangul/assets/19145342/e8d6001b-b661-4540-9f9c-665fa2450b84">

npm을 통해 github나 website로 접근하는 인플로우가 많을 것 같지는 않지만, 다른 경쟁 라이브러리들에는 이미 포함되어있는 필드들이라 `es-hangul`에도 포함되면 좋을 것 같습니다.

**Comment by okinawaa** [comment]
FYI : repository는 #77 에서 추가 되었습니다!
