### ISSUE TITLE
[Feature]: 호격조사 여/이여

### ISSUE THREAD

**Issue by stakbucks** [toss/es-hangul#82]
### Description

안녕하세요 :) 흥미롭게 보다가 받침 유무에 따라 달라지는 이형태 호격조사인 `여/이여`에 대한 처리가 없길래 이슈 남깁니다. 혹시 `여/이여`를 포함하지 않은 이유가 있을까요?

ex
그대'여' / 그대들'이여'
친구'여' / 사랑'이여'

cf. [여](https://ko.dict.naver.com/#/entry/koko/1868c527328147fbae3da7bb6d2cc399)

**Comment by evan-moon** [comment]
안녕하세요 @stakbucks 님! 큰 이유는 없는 것으로 알고 있고, 구어체에서는 자주 쓰는 용례가 아니다보니 빠진 것 같습니다 😅

**Comment by stakbucks** [comment]
> 안녕하세요 @stakbucks 님! 큰 이유는 없는 것으로 알고 있고, 구어체에서는 자주 쓰는 용례가 아니다보니 빠진 것 같습니다 😅

의도된 빠짐이었군요! 설명 감사합니다 🙇
