### ISSUE TITLE
[Feature]: trusted by 토스, 회사1, 회사2

### ISSUE THREAD

**Issue by manudeli** [toss/es-hangul#97]
### Description

trusted by 토스, 회사1, 회사2..

이런 화면이 README나 홈페이지에 적혀있다면 이 라이브러리를 좀 더 믿고 쓸 수 있을 거 같아요

https://github.com/orioncactus/pretendard?tab=readme-ov-file#pretendard%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94-%EA%B3%B3

<img width="976" alt="image" src="https://github.com/toss/es-hangul/assets/61593290/867e8ebc-f486-4782-b86a-a824c71991e7">

### Possible Solution

홈에 추가하면 좋을 거 같아요

**Comment by okinawaa** [comment]
오 신뢰도 향상 측면에서 너무 좋은 것 같아요.
1. 특정 회사가 사용하고 있다는 것을 어떻게 알 수 있을까요 
제보 같은것을 특정 통로를 통해서 받는것인지

**Comment by manudeli** [comment]
이슈 혹은 디스커션 혹은 다른 어떤 곳에 제보할 수 있는 채널이 있으면 좋겠어요

**Comment by younsl** [comment]
**FYI**: @okinawaa 다른 오픈소스 프로젝트의 경우, `ADOPTERS.MD` 파일에서 해당 오픈소스를 도입한 회사 목록을 관리하고 있고, 사용하는 유저가 PR로 직접 제출하는 형태로 목록이 관리되고 있습니다.

## 사용예시

- [Kyverno의 `ADOPTERS.md` 파일](https://github.com/kyverno/kyverno/blob/main/ADOPTERS.md)
- https://github.com/kyverno/kyverno/pull/9841

**Comment by okinawaa** [comment]
@manudeli 님, 아이디어 제안, 실제 구현까지 직접적인 도움 주셔서 정말 감사합니다 😆
